services:
  app:
    image: diogomarto/tmbdapi:latest
    build: API
    ports:
      - "${API_PORT:-8001}:${API_PORT:-8001}"
    environment:
      - API_PORT=${API_PORT:-8001}

  website:
    image: diogomarto/tmbdwebsite:latest
    build: website
    ports:
      - "${WEB_PORT:-9000}:${WEB_PORT:-9000}"
    environment:
      - API_URL=${API_URL:-http://localhost:8000}
      - WEB_PORT=${WEB_PORT:-9000}

  router:
    image: diogomarto/tmbdrouter:latest
    build: router
    ports:
      - "${ROUTER_PORT:-8000}:${ROUTER_PORT:-8000}"
    environment:
      - ROUTER_PORT=${ROUTER_PORT:-8000}
      - IP_API=app:${API_PORT:-8001}
      - IP_REPLICA1=${IP_REPLICA1:-}
      - IP_REPLICA2=${IP_REPLICA2:-}
      - IP_REPLICA3=${IP_REPLICA3:-}