services:
  app:
    image: diogomarto/tmbdapi:latest
    build: API
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    environment:
      - API_PORT=${API_PORT:-8000}

  website:
    image: diogomarto/tmbdwebsite:latest
    build: website
    ports:
      - "${WEB_PORT:-9000}:${WEB_PORT:-9000}"
    environment:
      - API_URL=${API_URL:-http://localhost:9000}
      - WEB_PORT=${WEB_PORT:-9000}