services:
  app:
    image: diogomarto/tmbdapi:latest
    build: API
    ports:
      - "8000:8000"
    environment:
      - API_PORT=${API_PORT:-8000}

  website:
    image: diogomarto/tmbdwebsite:latest
    build: website
    ports:
      - "80:80"
    environment:
      - API_URL=${API_URL:-http://localhost:8000}
      - WEB_PORT=${WEB_PORT:-8000}