name: Deploy to Remote Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check Docker credentials
        run: |
          echo "DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}"
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "DOCKER_PASSWORD is empty!"
            exit 1
          else
            echo "DOCKER_PASSWORD is set."
          fi
          echo "DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}"
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "DOCKER_PASSWORD is empty!"
            exit 1
          else
            echo "DOCKER_PASSWORD is set."
          fi
          
          
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the API image
      - name: Build and push API image
        run: |
          docker build -t diogomarto/tmbdapi:latest ./API
          docker push diogomarto/tmbdapi:latest
      
      - name: Build and push API image
        run: |
          docker build -t diogomarto/tmbdrouter:latest ./router
          docker push diogomarto/tmbdrouter:latest

      # Build and push the website image
      - name: Build and push website image
        run: |
          docker build -t diogomarto/tmbdwebsite:latest ./website
          docker push diogomarto/tmbdwebsite:latest

      # SSH into the remote server and restart services
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            cd ~/tmbd
            sudo docker-compose pull
            sudo docker-compose up -d
