name: Deploy to Remote Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Check out code
        uses: actions/checkout@v3

      - name: Echo 
        run: |
          echo "API URL: ${{ secrets.API_URL }}"
          echo "API PORT: ${{ secrets.API_PORT }}"
          echo "WEB PORT: ${{ secrets.WEB_PORT }}"
          echo "DOCKER USERNAME: ${{ secrets.DOCKER_USERNAME }}"
          echo "Length of API URL: ${#{ secrets.API_URL }}"
          echo "Length of API PORT: ${#{ secrets.API_PORT }}"
          echo "Length of WEB PORT: ${#{ secrets.WEB_PORT }}"
          echo "Length of DOCKER USERNAME: ${#{ secrets.DOCKER_USERNAME }}"
          

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the API image
      - name: Build and push API image
        run: |
          docker build -t diogomarto/tmbdapi:latest ./API
          docker push diogomarto/tmbdapi:latest

      # Build and push the website image
      - name: Build and push website image
        run: |
          docker build -t diogomarto/tmbdwebsite:latest ./website
          docker push diogomarto/tmbdwebsite:latest

      # SSH into the remote server and restart services
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            cd ~/tmbd
            export API_URL=http://${{ secrets.REMOTE_HOST }}/api
            export API_PORT=${{ secrets.API_PORT }}
            export WEB_PORT=${{ secrets.WEB_PORT }}
            docker-compose pull
            docker-compose up -d
